name: Build and Generate Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up COBOL environment
        run: |
          sudo apt-get update
          sudo apt-get -y install gnucobol
          sudo apt-get -y install doxygen

      - name: Compile COBOL code
        run: |
          cobc -x -o TriBulle TriBulle.cbl
          cobc -x -o Contact GestionnaireContact.cbl

      - name: Execute COBOL program
        run: |
          time ./TriBulle
          time ./Contact

      - name: Generate and upload artifact
        run: |
          date > execution_info.txt
          /usr/bin/time -o execution_info.txt -a -f "Execution time for TriBulle: %E" ./TriBulle
          /usr/bin/time -o execution_info.txt -a -f "Execution time for Contact: %E" ./Contact
          echo "Artifact created on $(date)" >> execution_info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: program-artifacts
          path: |
            ./artifact1
            ./artifact2
            execution_info.txt

      - name: Generate documentation
        run: |
          echo "INPUT = ." > Doxyfile
          echo "FILE_PATTERNS = *.cbl" >> Doxyfile
          echo "GENERATE_HTML = YES" >> Doxyfile
          echo "OUTPUT_DIRECTORY = docs" >> Doxyfile
          doxygen Doxyfile

      - name: Commit files
        run: |
          git config --local user.email "thibaut.lemichel@student.junia.com"
          git config --local user.name "ThibautLemichel"
          git add docs
          git commit -m "Documentation" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
